server:
  port: 8000
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: testuser
    password: pass1234
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update   # create, create-drop, update, none ? ??
      show-sql: true       # ???? SQL ??? ????
      properties:
        hibernate:
          format_sql: true # SQL ?? ?? ??
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "97f5c97a224dca533475fff3437be7d6"
            client-secret: "ABwe4xBoqluIt3O1aJ849qw3b3UUQv7q"
            redirect-uri: "http://172.16.101.234:3000/api/auth/callback/kakao"
#            redirect-uri: "http://localhost:3000/api/auth/callback/kakao"
#            redirect-uri: "http://localhost:5500/kakao-callback.html"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: "X9p$eTqN7#vF3@LmPz1!tUcRg*YkWqZ0oAsJdLxCvBnMhQeRfTgYhUjIkOlPnMbVcXsZaSdFgHiJkL11111"