global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8000']  # 로컬 Spring Boot 앱
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
